#define LV_LVGL_H_INCLUDE_SIMPLE
#include "icons\arrow_back_24.c\arrow_back_24.c"
#include "icons\close_48.c\close_48.c"
#include "icons\movie_48.c\movie_48.c"
#include "icons\quiz_48.c\quiz_48.c"
#include "icons\refresh_48.c\refresh_48.c"
#include "icons\settings_48.c\settings_48.c"
#include "icons\train_48.c\train_48.c"
#include "icons\monitor_heart_48.c\monitor_heart_48.c"
