#pragma once

#define WINSTON_STATISTICS
#define WINSTON_STATISTICS_SECONDS_PER_PRINT	(5)

#ifndef WINSTON_REALWORLD
#define WINSTON_RAILWAY_DEBUG_INJECTOR
#endif

#ifdef WINSTON_PLATFORM_WIN_x64
#define WINSTON_HAS_CHRONO
#endif

#define WINSTON_WITH_WEBSOCKET